### ISSUE TITLE
[Bug] Eleventy plugin doesn't generate any images

### ISSUE THREAD

**Issue by Defite** [nhoizey/images-responsiver#117]
**Describe the bug**
Eleventy plugin doesn't generate any images

**To Reproduce**

0. Remove all manually generated pictures, leave only source
1. Open last tutorial step (06), run `yarn start`
2. Install `node_modules`
3. Run `yarn start`
4. There is no images generated based on presets in `assets` folder

**Expected behavior**
Plugin generate all images from the preset and put it in `assets` folder

**Comment by freshyill** [comment]
This definitely doesn't generate images for me… but should it? Is this only for generating markup for images that I need to generate by some other method? It's not clear if this is a bug or the intended behavior.

**Comment by nhoizey** [comment]
@Defite @freshyill really sorry for the laaate answer.

Indeed, this plugin doesn't generate any image.

It is meant to be used with another solution for image resizing and optimization, like an image CDN. I'm currently using Cloudinary for example, but it works well with others.

I think it should be possible to use it with [the official Eleventy Image plugin](https://www.11ty.dev/docs/plugins/image/), if you don't want to rely on a third party service, but I didn't check.

I'll add a warning to the README and docs.
