### ISSUE TITLE
Links in the npm package description 404 [Bug] 

### ISSUE THREAD

**Issue by tomglynch** [nhoizey/images-responsiver#139]
**Describe the bug**
Links in the npm package description all 404

**To Reproduce**

1. go to https://www.npmjs.com/package/eleventy-plugin-images-responsiver
2. Click links under the heading Usage
3. Links all 404

**Expected behavior**
Links to a page describing how to use

**Comment by nhoizey** [comment]
@tomglynch thanks for the report! 🙏

I'm really sorry for the late fix.
