### ISSUE TITLE
eleventy package: bump eleventy version

### ISSUE THREAD

**Issue by inetbiz** [nhoizey/images-responsiver#236]
**Is your feature request related to a problem? Please describe.**
Eleventy package uses an older version of `@11ty/eleventy`
https://github.com/nhoizey/images-responsiver/blob/main/packages/eleventy-plugin-images-responsiver/package.json#L37-L38
```
  "peerDependencies": {
    "@11ty/eleventy": "^0.12.1"
  },
```
**Describe the solution you'd like**
```
  "peerDependencies": {
    "@11ty/eleventy": "^1.0.0"
  },
```

**Comment by nhoizey** [comment]
Hi @inetbiz, sorry for the late answer, this is done.
