### ISSUE TITLE
[Bug] Enable Eleventy 2.0 install without dependency warnings

### ISSUE THREAD

**Issue by aarongustafson** [nhoizey/images-responsiver#305]
**Describe the bug**
NPM install of Eleventy 2.0.0 issues warnings

**To Reproduce**

1. Attempt to upgrade Eleventy via npm

**Expected behavior**
Eleventy install issues no warnings

**Screenshots / logs**
```
npm WARN Could not resolve dependency:
npm WARN peer @11ty/eleventy@">= 0.12.1 < 2" from eleventy-plugin-images-responsiver@1.12.0
```

**Environment**

- OS and version: macOS 13.2
- Eleventy version: 2.0.0
- `eleventy-plugin-images-responsiver` version: 1.12.0

**Comment by nhoizey** [comment]
@aarongustafson sorry Aaron, I missed this issue, but it's now fixed in release 2.0.0 of the plugin! 🥳
