### ISSUE TITLE
Legitimate bug fix in basicHTML breaks images-responsiver

### ISSUE THREAD

**Issue by nhoizey** [nhoizey/images-responsiver#72]
I currently load the full HTML document in BasicHTML like this:

```javascript
const html = "<!DOCTYPE html><html><body><p>Hello</p></body></html>";
document.documentElement.innerHTML = html;
```

Unfortunately, this worked before because there was an issue in BasicHTML.

Now, this leads to duplicate `<html>` tags in the result:
https://github.com/WebReflection/basicHTML/issues/51#issuecomment-683682147

Any advice on how to reliably filter out `<!DOCTYPE html><html>` and `</html>` from the input string, assuming there can be many DOCTYPES, and attributes in `<html>`?

**Comment by nhoizey** [comment]
Actually, the DOCTYPE and `<html>` attributes should be restored after `image-reponsiver` has done its work.

**Comment by nhoizey** [comment]
This could be a (convoluted) solution:

```javascript
const basicHTML = require('basichtml');
const { document } = basicHTML.init();
const regex = /^([\S\s]*?<html[\S\s]*?>)([\S\s]*?)(<\/html>[\S\s]*?)$/im;

const html = `<!DOCTYPE html>
<html lang='fr'>
<body>
<p>Hello</p>
</body>
</html>`;

let srcMatches = html.match(regex);
console.dir(srcMatches);

document.documentElement.innerHTML = srcMatches[2];
destMatches = document.toString().match(regex);
console.dir(destMatches);

console.log('Result:');
console.log(srcMatches[1], destMatches[2], srcMatches[3]);
```

**Comment by nhoizey** [comment]
We could also use [split-html](https://github.com/apostrophecms/split-html), but it uses Cheerio.

We already [replaced JSDOM with BasicHTML](https://github.com/nhoizey/images-responsiver/commit/47d9f66734ceda75d0e010540a9020ac8af2da77), let's see if a third lib is even better… 🤷‍♂️

**Comment by WebReflection** [comment]
I don't understand the use case for multiple `<html>` tags in a string, as AFAIK that's an invalid document/page ... what are you trying to do?

**Comment by WebReflection** [comment]
Another solution could be this one:

```js
const {document} = require('../basichtml.js').init();

const html = "<!DOCTYPE html><html lang='fr'><body><p>Hello</p></body></html>";

const tmp = document.createElement('div');
tmp.innerHTML = html;
const {attributes, children} = tmp.firstElementChild;

document.documentElement.textContent = '';
document.documentElement.attributes = attributes;
document.documentElement.append(...children);
console.log(document.toString());
```

yet, if you are parsing multiple `<html>` per document I think you are going to have an issue.

**Comment by WebReflection** [comment]
as utility, you could also use this instead:

```js
const {Document} = require('../basichtml.js');
function createDocumentFromHTML(html, customElements) {
  const document = new Document(customElements);
  const tmp = document.createElement('div');
  tmp.innerHTML = html;
  const {attributes, children} = tmp.firstElementChild;
  document.documentElement.attributes = attributes;
  document.documentElement.append(...children);
  return document;
}
```

**Comment by nhoizey** [comment]
> I don't understand the use case for multiple `<html>` tags in a string

I don't want multiple `<html>` tags, that's what BasicHTML now gives me when I put a full HTML document in `document.documentElement.innerHTML`. And I understand why, you're right that `documentElement` should contain neither the `DOCTYPE` nor the `<html>`.

**Comment by nhoizey** [comment]
> ```js
> const tmp = document.createElement('div');
> tmp.innerHTML = html;
> ```

It looks like it work, even if I'm a bit hesitating to put a full HTML document inside a `<div>`… 😅

**Comment by nhoizey** [comment]
> as utility, you could also use this instead:

It looks like it solves my issue, thanks a lot! 🙏

**Comment by WebReflection** [comment]
> It looks like it works, even if I'm a bit hesitating to put a full HTML document inside a `<div>`… sweat_smile

*basicHTML* knows nothing about `div` and others ... they are all nodes, no special meaning. The `document` instance though has some constrain to simulate the DOM ... but *basicHTML* ain't *JSDOM*, it's not about standard simulation, it's about being useful for SSR and Web Workers 😉

**Comment by nhoizey** [comment]
Ok, now I understand, thanks!

You can had SSG (Static Site Generators) to the usage target! 👍

**Comment by WebReflection** [comment]
> It looks like it solves my issue, thanks a lot! pray

glad it worked, but is there any reason to keep this bug open, if it did?

**Comment by nhoizey** [comment]
@WebReflection my local tests show it works, but I didn't use it in this library code yet.

**Comment by nhoizey** [comment]
@WebReflection I was previously using this code to initialize BasicHTML:

```javascript
const { document } = basicHTML.init({
  selector: {
    // use the module sizzle, it will be required
    // automatically
    name: 'sizzle',
    // how to retrieve results => querySelectorAll
    $(Sizzle, element, css) {
      return Sizzle(css, element);
    },
  },
});

document.documentElement.innerHTML = html;
```

I don't understand how to add Sizzle in [the function](https://github.com/nhoizey/images-responsiver/issues/72#issuecomment-684769928) you provided 2 days ago. 🤷‍♂️

**Comment by WebReflection** [comment]
```js
const $ = require('sizzle');
require('basichtml/src/utils').querySelectorAll = function (css, element = this) {
  return $(css, element);
};
const {Document} = require('basichtml');
function createDocumentFromHTML(html, customElements) {
  const document = new Document(customElements);
  const tmp = document.createElement('div');
  tmp.innerHTML = html;
  const {attributes, children} = tmp.firstElementChild;
  document.documentElement.attributes = attributes;
  document.documentElement.append(...children);
  return document;
}
```

**Comment by nhoizey** [comment]
@WebReflection thanks for your help.

Unfortunately, this gives me a `window is not defined` error with Sizzle:

```
/Users/nhoizey/Documents/Devs/_bidouilles/basichtml/node_modules/sizzle/dist/sizzle.js:2478
} )( window );
     ^

ReferenceError: window is not defined
    at Object.<anonymous> (/Users/nhoizey/Documents/Devs/_bidouilles/basichtml/node_modules/sizzle/dist/sizzle.js:2478:6)
    at Module._compile (internal/modules/cjs/loader.js:1118:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:1138:10)
    at Module.load (internal/modules/cjs/loader.js:982:32)
    at Function.Module._load (internal/modules/cjs/loader.js:875:14)
    at Module.require (internal/modules/cjs/loader.js:1022:19)
    at require (internal/modules/cjs/helpers.js:72:18)
    at Object.<anonymous> (/Users/nhoizey/Documents/Devs/_bidouilles/basichtml/index.js:34:11)
    at Module._compile (internal/modules/cjs/loader.js:1118:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:1138:10)
```

Would you recommend not using Sizzle with basicHTML?

I currently use a pretty complex selector: `':not(picture) img[src]:not([srcset]):not([src$=".svg"])'`

**Comment by WebReflection** [comment]
> @WebReflection thanks for your help.
> 
> Unfortunately, this gives me a `window is not defined` error with Sizzle:

well, that's another issue .... but nothing stops you from writing `return (global.window = {document});` at the end of that function and call it a day, right?

**Comment by nhoizey** [comment]
I'm really lost here… 😭

Here's my current `index.js` script:

```javascript
global.window = global;

const $ = require("sizzle");

require("basichtml/src/utils").querySelectorAll = function(
  css,
  element = this
) {
  return $(css, element);
};

const { Document } = require("basichtml");

function createDocumentFromHTML(html, customElements) {
  const document = new Document(customElements);
  const tmp = document.createElement("div");
  tmp.innerHTML = html;
  const { attributes, children } = tmp.firstElementChild;
  document.documentElement.attributes = attributes;
  document.documentElement.append(...children);
  return document;
}

const html = `<!DOCTYPE html>
<html lang='fr' toto=2>
<body class="yet">
<p>Hello <img src="foo.png"></p>
<picture>
  <source srcet="bar.png" media="(min-width: 800px)">
  <img src="baz.jpg">
</picture>
</body>
</html>`;

let document = createDocumentFromHTML(html);
[
  ...document.querySelectorAll(
    ':not(picture) img[src]:not([srcset]):not([src$=".svg"])'
  )
].forEach(image => {
  console.dir(image);
});
console.log(document.toString());
```

And here's what I get in the terminal when running `node index.js`:

```
/Users/nhoizey/Documents/Devs/_bidouilles/basichtml/node_modules/sizzle/dist/sizzle.js:414
	var el = document.createElement( "fieldset" );
	                  ^

TypeError: Cannot read property 'createElement' of undefined
    at assert (/Users/nhoizey/Documents/Devs/_bidouilles/basichtml/node_modules/sizzle/dist/sizzle.js:414:20)
    at /Users/nhoizey/Documents/Devs/_bidouilles/basichtml/node_modules/sizzle/dist/sizzle.js:2403:24
    at Object.<anonymous> (/Users/nhoizey/Documents/Devs/_bidouilles/basichtml/node_modules/sizzle/dist/sizzle.js:2478:4)
    at Module._compile (internal/modules/cjs/loader.js:1118:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:1138:10)
    at Module.load (internal/modules/cjs/loader.js:982:32)
    at Function.Module._load (internal/modules/cjs/loader.js:875:14)
    at Module.require (internal/modules/cjs/loader.js:1022:19)
    at require (internal/modules/cjs/helpers.js:72:18)
    at Object.<anonymous> (/Users/nhoizey/Documents/Devs/_bidouilles/basichtml/index.js:24:11)
```

I'm really new to Node.js…

**Comment by WebReflection** [comment]
```js
function createDocumentFromHTML(html, customElements) {
  const document = new Document(customElements);
  const tmp = document.createElement("div");
  tmp.innerHTML = html;
  const { attributes, children } = tmp.firstElementChild;
  document.documentElement.attributes = attributes;
  document.documentElement.append(...children);
  return (window.document = document);
}
```

**Comment by WebReflection** [comment]
alternatively, you need to make the `document` global each time Sizzle gets used ... but since it was working before, my suggestion should already fix it

**Comment by nhoizey** [comment]
I still get the `TypeError: Cannot read property 'createElement' of undefined` error, I really don't understand anything anymore… 😥

I can keep basicHTML 2.2.9, or try something else like Cheerio…

**Comment by WebReflection** [comment]
Yeah, as I have zero ways to easily reproduce your issue, try anything else you like

**Comment by nhoizey** [comment]
I like basicHTML, I would so like to be able to keep using it.

But if you don't get the same error as me with this script (built from your multiple helps), I really don't understand where to look…

```javascript
global.window = global;

const $ = require("sizzle");

require("basichtml/src/utils").querySelectorAll = function(
  css,
  element = this
) {
  return $(css, element);
};

const { Document } = require("basichtml");

function createDocumentFromHTML(html, customElements) {
  const document = new Document(customElements);
  const tmp = document.createElement("div");
  tmp.innerHTML = html;
  const { attributes, children } = tmp.firstElementChild;
  document.documentElement.attributes = attributes;
  document.documentElement.append(...children);
  return (window.document = document);
}

const html = `<!DOCTYPE html>
<html lang='fr' toto=2>
<body class="yet">
<p>Hello <img src="foo.png"></p>
<picture>
  <source srcet="bar.png" media="(min-width: 800px)">
  <img src="baz.jpg">
</picture>
<img src="another.svg" />
</body>
</html>`;

let document = createDocumentFromHTML(html);
[
  ...document.querySelectorAll('img[src]:not([srcset]):not([src$=".svg"])')
].forEach(image => {
  console.dir(image);
});
console.log(document.toString());
```

Here's what I get:

```
/Users/nhoizey/Documents/Devs/_bidouilles/basichtml/node_modules/sizzle/dist/sizzle.js:414
	var el = document.createElement( "fieldset" );
	                  ^

TypeError: Cannot read property 'createElement' of undefined
    at assert (/Users/nhoizey/Documents/Devs/_bidouilles/basichtml/node_modules/sizzle/dist/sizzle.js:414:20)
    at /Users/nhoizey/Documents/Devs/_bidouilles/basichtml/node_modules/sizzle/dist/sizzle.js:2403:24
    at Object.<anonymous> (/Users/nhoizey/Documents/Devs/_bidouilles/basichtml/node_modules/sizzle/dist/sizzle.js:2478:4)
    at Module._compile (internal/modules/cjs/loader.js:1118:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:1138:10)
    at Module.load (internal/modules/cjs/loader.js:982:32)
    at Function.Module._load (internal/modules/cjs/loader.js:875:14)
    at Module.require (internal/modules/cjs/loader.js:1022:19)
    at require (internal/modules/cjs/helpers.js:72:18)
    at Object.<anonymous> (/Users/nhoizey/Documents/Devs/_bidouilles/basichtml/basic-2.3.0.js:3:11)
```

**Comment by WebReflection** [comment]
The error is in Sizzle, which tries to access the document before you attach one to the global.

Move sizzle require in a lazy fashion wai within the querySelectorAll and you should be ok.

I just don’t like much the “if it breaks I’ll use something else” attitude ...

**Comment by nhoizey** [comment]
I really understand your feeling about "if it breaks I’ll use something else", but if I'm not able to use a tool, even after trying for many hours, I sometimes have to move on, this is no judgment of the quality of the tool I didn't manage to use.

I'm really sorry, and very thankful for your help. 🙏

Unfortunately, I'm very bad at JavaScript, and Node.js specifically, so I mostly follow tutorials, copy/paste some code fragments, but not always understand what I'm doing. And here, I don't understand anything at all, since v2.3.0.

By the way, I move Sizzle require inside the `querySelectorAll` function, and it looks like I don't have the error anymore. 🎉

So thanks a lot again for your help and patience. 🙏

And sorry for my grumpiness… 😔

**Comment by nhoizey** [comment]
@WebReflection I've been able to upgrade to basicHTML 2.3.0 and release a new version of my library, thanks again! 🙏
