### ISSUE TITLE
Unicode characters inside templates don't get encoded when plugin is enabled

### ISSUE THREAD

**Issue by fabiomrbarbosa** [nhoizey/images-responsiver#78]
When the plugin is enabled, Unicode characters that I can otherwise type as HTML codes do not get encoded into their corresponding characters in the final output. 

This means, for instance, that typing `&copy;` into my footer's Nunjucks partial template means that the character never gets converted to a copyright symbol. I have to explicitly type `©` into my template in order for it to work.

I'm running `@11ty/eleventy ^0.11.0` and `eleventy-plugin-images-responsiver ^1.5.3`. I've detected the issue by turning all other plugins and imports inside my `.eleventy.js` file. I can reproduce the issue regardless of what is present in my `images-responsiver` config. 

I've moved on to a custom shortcode component, but the relevant files are referred to in this commit: https://github.com/fabiomrbarbosa/fabiomrbarbosa.com/commit/caae0df2191181036c0fbaf9ebb80af31292f68f

Thanks in advance.

**Comment by nhoizey** [comment]
It looks like I now have the same issue with `&nbsp;`.

I need to find a way to fix this.

**Comment by nhoizey** [comment]
This should be fixed when BasicHTML will be replaced with LinkeDOM: #138

**Comment by nhoizey** [comment]
This should now be fixed since v1.9.0

@fabiomrbarbosa @Rostiger can you confirm?
