### ISSUE TITLE
Extraneous <html> tag in final code when plugin is enabled

### ISSUE THREAD

**Issue by fabiomrbarbosa** [nhoizey/images-responsiver#79]
I implemented this plugin on my current Eleventy project and I've realised that the final html output gets an extra `<html>` tag, completely ignoring the one already present in my code, like so:

```
<!DOCTYPE html><html>
<html lang="en">

<!-- content goes here -->

</html><!-- my own -->
</html><!-- the plugin's -->
```

I'm running `@11ty/eleventy ^0.11.0` and `eleventy-plugin-images-responsiver ^1.5.3`. I've detected the issue by turning all other plugins and imports inside my `.eleventy.js` file. I can reproduce the issue regardless of what is present in my `images-responsiver` config. Removing the `doctype` and `<html>` tag entirely from my templates means they are generated again, minus my personal attributes, in the final output.

I've since moved on to a custom shortcode component, but the relevant files are referred to in this commit: https://github.com/fabiomrbarbosa/fabiomrbarbosa.com/commit/caae0df2191181036c0fbaf9ebb80af31292f68f

Thanks in advance for your attention.

**Comment by nhoizey** [comment]
@fabiomrbarbosa this should be fixed in latest release

**Comment by dirtystylus** [comment]
Was also experiencing this, can confirm that update to v1.8.2 fixed it.

**Comment by nhoizey** [comment]
@dirtystylus thanks!
